version: '3.4'

services:
  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
      - seq

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
