version: '3.4'

services:
  web.api: # Service for the Web API
    image: ${DOCKER_REGISTRY-}webapi # Docker image for the Web API
    build:
      context: . # Build context
      dockerfile: Web.Api/Dockerfile # Path to the Dockerfile
    ports:
      - "5000:80" # Port mapping
    depends_on:
      - mongodb # Dependency on MongoDB service
      - seq # Dependency on Seq service

  mongodb: # Service for MongoDB
    image: mongo # Docker image for MongoDB
    ports:
      - "27017:27017" # Port mapping for MongoDB

  seq: # Service for Seq
    image: datalust/seq:latest # Docker image for Seq
    ports:
      - "5341:5341" # Port mapping for Seq
